apiVersion: v1
kind: Pod
metadata:
  name: no-resources
  labels:
    app.kubernetes.io/name: demo
    owner: team-a
    env: dev
spec:
  containers:
    - name: app
      image: registry.company.com/demo/app:1.0.0
      readinessProbe:
        httpGet:
          path: /healthz
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 10
      livenessProbe:
        httpGet:
          path: /healthz
          port: 8080
        initialDelaySeconds: 15
        periodSeconds: 20